# Generated by Django 5.1.7 on 2025-03-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='orders',
        ),
        migrations.AddField(
            model_name='addres',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address', to='api.profile'),
        ),
        migrations.AddField(
            model_name='boottype',
            name='boot_type',
            field=models.CharField(choices=[('Campo', 'Campo'), ('Salão', 'Salão'), ('Suiço', 'Suiço'), ('Trava Mista', 'Trava Mista')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='addres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.addres'),
        ),
        migrations.AddField(
            model_name='order',
            name='chuteira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.boottype'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile'),
        ),
    ]
