# Generated by Django 5.1.7 on 2025-03-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_soccerboot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soccerboot',
            name='type',
        ),
        migrations.AddField(
            model_name='soccerboot',
            name='boot_type',
            field=models.CharField(choices=[('Campo', 'Campo'), ('Salão', 'Salão'), ('Suiço', 'Suiço'), ('Trava Mista', 'Trava Mista')], max_length=11, null=True),
        ),
        migrations.DeleteModel(
            name='BootType',
        ),
    ]
