# Generated by Django 5.1.7 on 2025-03-26 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_soccerboot_type_soccerboot_boot_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.IntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.soccerboot')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
