# Generated by Django 5.1.7 on 2025-03-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bootincart_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootincart',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
