# Generated by Django 5.1.7 on 2025-03-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bootincart_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootincart',
            old_name='ip',
            new_name='cart_id',
        ),
    ]
