# Generated by Django 5.1.7 on 2025-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_ip_bootincart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootincart',
            name='cart_id',
            field=models.CharField(max_length=39),
        ),
    ]
