# Generated by Django 5.1.7 on 2025-04-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_bootincart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soccerboot',
            name='boot_type',
            field=models.CharField(choices=[('Campo', 'Campo'), ('Salao', 'Salão'), ('Suiço', 'Suiço'), ('Trava-Mista', 'Trava Mista')], max_length=11, null=True),
        ),
    ]
