# Generated by Django 5.1.7 on 2025-04-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_soccerboot_boot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=11),
        ),
    ]
