# Generated by Django 5.1.7 on 2025-04-09 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_brand_brand_alter_color_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootincart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soccer_boots', to='api.soccerboot'),
        ),
    ]
