# Generated by Django 5.1.7 on 2025-04-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bootincart_ammount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootincart',
            old_name='ammount',
            new_name='amount',
        ),
    ]
