# Generated by Django 5.1.7 on 2025-04-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_ammount_bootincart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootincart',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
