# Generated by Django 5.1.7 on 2025-04-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_bootincart_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addres',
            new_name='Address',
        ),
    ]
