# Generated by Django 5.1.7 on 2025-04-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_order_soccerboot_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soccerboot',
            name='size',
        ),
        migrations.AddField(
            model_name='bootincart',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
