# Generated by Django 5.1.7 on 2025-04-11 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_soccerboot_size_bootincart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_address', to='api.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='boots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boots_in_cart', to='api.bootincart'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
