# Generated by Django 5.1.7 on 2025-04-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_order_address_order_boots_order_last_name_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='boots',
        ),
        migrations.AddField(
            model_name='order',
            name='boots',
            field=models.ManyToManyField(null=True, related_name='orders', to='api.bootincart'),
        ),
    ]
