# Generated by Django 5.1.7 on 2025-04-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_address_order_address_remove_order_boots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='boots',
            field=models.ManyToManyField(related_name='orders', to='api.bootincart'),
        ),
    ]
