# Generated by Django 5.1.7 on 2025-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_address_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='boots',
            field=models.ManyToManyField(related_name='orders', to='api.soccerboot'),
        ),
    ]
