# Generated by Django 5.1.7 on 2025-04-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_order_boots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='boots',
        ),
        migrations.AddField(
            model_name='soccerboot',
            name='oders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boots', to='api.order'),
        ),
        migrations.AlterField(
            model_name='bootincart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soccer_boots', to='api.soccerboot'),
        ),
    ]
