# Generated by Django 5.1.7 on 2025-04-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_order_boots_soccerboot_oders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=12),
        ),
    ]
