# Generated by Django 5.1.7 on 2025-04-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_color_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(max_length=7),
        ),
    ]
