# Generated by Django 5.1.7 on 2025-04-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_question_alter_color_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='soccerboot',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
