# Generated by Django 5.1.7 on 2025-04-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_color_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
