# Generated by Django 5.1.7 on 2025-04-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
