# Generated by Django 5.2 on 2025-04-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_profile_birth_date_alter_profile_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
